version: '3.4'

services:
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRE_DB=DiscountDb
    restart: always
    ports:
      -  "5432:5432"
    volumes:
      -  postgres_data:/var/lib/postgressql/data/







